version:  "3.7"

services:
  db:
    build: database
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - local
    ports:
      - "3306:3306"
    restart: always

  app:
    build: .
    depends_on:
      - db
    networks:
      - local
    ports:
      - "5005:5005"
      - "8080:8080"

networks:
  local:

